name = "blogdown-tufte"
license = "MIT"
licenselink = "https://github.com/mps9506/blogdown-tufte/blob/master/LICENSE.md"
description = "Hugo/Blogdown theme heavily inspired by Tufte but customized."
homepage = "https://github.com/mps9506/blogdown-tufte"
tags = ["blogdown", "tufte", "minimal"]
features = ["math", "tufte-css", "tufte"]
min_version = 0.01

[author]
  name = "Michael Schramm"
  homepage = "http://michaelpaulschramm.com"

# If porting an existing theme
[original]
  name = "tuftesque"
  homepage = "https://github.com/nstrayer/tuftesque"
  repo = "https://github.com/nstrayer/tuftesque"