baseurl = "/"
languageCode = "en-us"
title = "A Hugo website"
theme = "blogdown-tufte"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/About/"
[[menu.main]]
    name = "CV"
    url = "/CV/"

[params]
    description = "A website built through Hugo and blogdown."
	showPoweredBy = true
    copyrightHolder = "John Doe"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 320
    height = 137
    alt = "Logo"
	
	# social icons used in footer
	# can use any font awesome icon: http://fontawesome.io/icons/
    [[params.social]]
    name = "GitHub"
    icon = "github"
    link = "https://github.com/rstudio/blogdown"
    [[params.social]]
    name = "Twitter"
    icon = "twitter"
    link = "https://twitter.com/rstudio"
    [[params.social]]
    name = "LinkedIn"
    icon = "linkedin-square"
    link = "https://www.linkedin.com/"
    [[params.social]]
    name = "Instagram"
    icon = "instagram"
    link = "https://www.instagram.com/"
